### ISSUE TITLE
Additional hooking feature for phase 2: `--test` file discovery to include additional file extensions

### ISSUE THREAD

**Issue by cspotcode** [nodejs/loaders#106]
I haven't used node's new `--test` myself, but a feature request prompted me to look at it.

https://nodejs.org/dist/latest-v18.x/docs/api/test.html#test-runner-execution-model

It looks like `node --test subdirectory/` will discover all files within `subdirectory/` matching certain naming conventions, and with `.js`, `.cjs`, or `.mjs` file extension.

A suite of customization hooks would want to somehow augment this matching behavior to include `.cts`, `.mts`, `.tsx`, and `.jsx`, and to exclude `.d.ts`.

**Comment by GeoffreyBooth** [comment]
It looks like this is being discussed in https://github.com/nodejs/node/issues/44023. If you don’t mind, can we close this issue and keep the discussion in that one? And based on how that thread eventually resolves, you could open a PR against the README on this repo to add a TODO item for whatever they decide (if the consensus solution is in our scope).
