### ISSUE TITLE
Sharing custom context between hooks

### ISSUE THREAD

**Issue by bpstrngr** [nodejs/loaders#127]
Couldn't see if anyone encountered this before, but i'm having an issue with passing context created in the resolve hook on to the load hook. My only naive option was to try assigning it to the object returned by nextResolve, but the properties beyond url and format are nowhere to be found in the load hook's arguments. My specific use case is resolving an alias specifier to an url, that also defines some transpilation instructions from the alias configuration, but this can't be recovered again from the resolved url in the load step anymore, where they would need be applied on the file contents. Would it be reasonable to allow some custom context properties to travel between the hooks? I could implement an ugly reverse-engineering from the resolved url given there's hope for this to become supported. Or could it be that the "format" property is intended to be capable of covering such use cases? Because the other option is to define specific sets of transpilation instructions as "format"-s, which can then act as references to the missing instructions (the need to reference transpilation instructions already suggests they're not intact es "module"-s after all).

**Comment by bpstrngr** [comment]
nota bene custom format specifiers are not supported at the moment either ("ERR_UNKNOWN_MODULE_FORMAT" at ESMLoader.moduleProvider (loader:334:15)).

**Comment by GeoffreyBooth** [comment]
Can you just store it in the scope of your loader?

```js
/** @type {Map<string, object>} */
const customUrlContexts = new Map()

export function resolve(specifier, context, next) {
  const result = next(specifier)
  const { url } = result
  customUrlContexts.set(url, { yourCustomContextData: 'here' })
  return result
}

export async function load(url, context, next) {
  const customUrlContext = customUrlContexts.get(url)
  customUrlContexts.delete(url)
  // do stuff
}
```

**Comment by bpstrngr** [comment]
taking advantage of the "format" property as i realized in the end suited me perfectly, but then you're right, higher scope is also a solution i couldn't reasonably object.
