### ISSUE TITLE
remove @flarna from loader group

### ISSUE THREAD

**Issue by Flarna** [nodejs/loaders#133]
I joined the meetings a few times but actually found no time to get really involved.

Besides that I have some different assignments meanwhile so I think it's time to remove myself from the corresponding github team.

Don't what exactly is needed to get this done.

**Comment by GeoffreyBooth** [comment]
I've removed you. I think the only consequence is that you'll stop receiving GitHub notifications when the team is tagged. If you'd like to start receiving those again please let me know and I'll add you back.
