### ISSUE TITLE
Node.js Loaders Team Meeting 2024-07-12

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/loaders#211]
## Time

**UTC Fri 12-Jul-2024 16:00 (04:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Fri 12-Jul-2024 09:00 (09:00 AM) |
| US / Mountain | Fri 12-Jul-2024 10:00 (10:00 AM) |
| US / Central  | Fri 12-Jul-2024 11:00 (11:00 AM) |
| US / Eastern  | Fri 12-Jul-2024 12:00 (12:00 PM) |
| EU / Western  | Fri 12-Jul-2024 17:00 (05:00 PM) |
| EU / Central  | Fri 12-Jul-2024 18:00 (06:00 PM) |
| EU / Eastern  | Fri 12-Jul-2024 19:00 (07:00 PM) |
| Moscow        | Fri 12-Jul-2024 19:00 (07:00 PM) |
| Chennai       | Fri 12-Jul-2024 21:30 (09:30 PM) |
| Hangzhou      | Sat 13-Jul-2024 00:00 (12:00 AM) |
| Tokyo         | Sat 13-Jul-2024 01:00 (01:00 AM) |
| Sydney        | Sat 13-Jul-2024 02:00 (02:00 AM) |

Or in your local time:
* https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Node.js%20Loaders%20team+Meeting+2024-07-12&iso=20240712T1600
* or https://www.wolframalpha.com/input/?i=04PM+UTC%2C+Jul+12%2C+2024+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/1RjmpwmsCoqg7o4QDvNzds3lCFhjqWBSToCvBgfUY8mY/edit>

## Agenda

Extracted from **loaders-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

* https://github.com/nodejs/node/pull/53725
* https://github.com/nodejs/loaders/issues/208
* https://github.com/nodejs/loaders/pull/210

## Invited

* Loaders team: @nodejs/loaders
* @marco-ippolito
* @kdy1
* @DanielRosenwasser
* @robpalme

## Joining the meeting

* link for participants: [zoom.us/j/97506450082](https://zoom.us/j/97506450082)

* For those who just want to watch: [youtube.com/c/nodejs+foundation/live](https://www.youtube.com/c/nodejs+foundation/live)

**Comment by JakobJingleheimer** [comment]
Are we not meeting at our regularly scheduled time on Tuesday, 16 July?

(I will be on an aeroplane at this new time)

**Comment by GeoffreyBooth** [comment]
There can be a meeting at that time, too, but I can’t attend that one. This one is ad hoc because @DanielRosenwasser asked to discuss the TypeScript work, and I asked yesterday at https://openjs-foundation.slack.com/archives/C053UCCP940/p1720494523190599 if there was another time that could work.

**Comment by JakobJingleheimer** [comment]
Ah, sorry. Just saw that from earlier today (very busy day at work).

Sure, carry on 🙂
