### ISSUE TITLE
List of loaders in the wild today

### ISSUE THREAD

**Issue by cspotcode** [nodejs/loaders#8]
The goal of this issue is to track a list of loaders used in the wild today.  Eventually, we will need to decide how loaders compose and interop.  It will be helpful to keep track of what loaders are doing today so we understand how to support their use-cases.

This list is very short to start, but I'll do my best to ask around in forums and mention this issue to the authors.

### Yarn2 PnP
- Currently in a draft PR
- Issue: yarnpkg/berry#638
- Pull request: yarnpkg/berry#2161
- Author is waiting to see how node design work proceeds: https://github.com/yarnpkg/berry/pull/2161#issuecomment-841713037

### ts-node
- First released in [v8.10.0](https://github.com/TypeStrong/ts-node/releases/tag/v8.10.0) as an experimental feature to match node's experimental status
- Documentation, feedback, Q&A in this thread: TypeStrong/ts-node#1007

### @istanbuljs/esm-loader-hook

- [NPM](https://www.npmjs.com/package/@istanbuljs/esm-loader-hook)
- I don't know if this is commonly used.  I need to ask the authors

### Jest

- [Docs](https://jestjs.io/docs/ecmascript-modules)
- Issue: facebook/jest#9430

### multiloader

- Compose multiple loaders into one
- https://github.com/targos/multiloader

### quibble
- used by the mocking library testdouble for mocking ESM
- https://github.com/testdouble/quibble

### babel-register-esm

- babel transpiler hook
- https://github.com/giltayar/babel-register-esm

**Comment by cspotcode** [comment]
I should also add to this list CommonJS loaders that cannot be implemented as ESM loaders, because they indicate features which should be added to the ESM loader APIs.

**Comment by giltayar** [comment]
The `quibble` loader, which is used by the mocking library `testdouble` for mocking ESM: https://github.com/testdouble/quibble.

**Comment by giltayar** [comment]
`babel-register-esm`: https://github.com/giltayar/babel-register-esm, which is a loader we use at our company that transpiles source code according to the babel configuration.

**Comment by GeoffreyBooth** [comment]
Do you mind opening a PR to add this info to https://github.com/nodejs/loaders/blob/main/doc/resources.md?

**Comment by cspotcode** [comment]
Yes, I'll do that, I didn't notice that list before creating this PR.  My mistake.

**Comment by giltayar** [comment]
Of course. Although I did notice you put my blog post in there. :-)

**Comment by giltayar** [comment]
PR #10 for `babel-register-esm`
